### ISSUE TITLE
Python3.6 compatibility release

### ISSUE THREAD

**Issue by chriswue** [gweis/isodate#43]
Are there any plans to release a Python3.6 compatible version? The current 0.5.4 release unfortunately makes use of `long` (not sure if there are other incompatibilities) which makes the code crash on Python 3.6. 

The current isodate master has this fixed but it's tagged as 0.6 dev. Any plans to release the current version at some point or maybe make a 0.5.5 with the 3.6 fixes backported?

**Comment by lmazuel** [comment]
@chriswue FYI, during installation 2to3 is called in 0.5.4, so it's working on 3.6 (I use it out-of-the-box).

The only difference with current master, is that 2to3 is removed (and then the code adapted accordingly). Since 2to3 was creating problems on some environment (I don't own anything here, but I discussed about it with the owner)

**Comment by chriswue** [comment]
@Imazuel: Hm, interesting. I just tried it on a vanilla python 3.6.3 install and indeed that works. The machine we had trouble on was installed with python 3.5 originally and then upgraded to 3.6 later (windows platform).

**Comment by chriswue** [comment]
@Imazuel: Hm, interesting. I just tried it on a vanilla python 3.6.3 install and indeed that works. The machine we had trouble originally had Python 2.7 and later Python 3.5 and mysteriously that worked. Just adding Python 3.6 on top made it fall over - maybe it picked up the 2.7 package files for some reason
