### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Flix6x** [gweis/isodate#65]
I see no more PRs merged since 2018. Is this very nice project still maintained or looking for a new maintainer?

**Comment by hugovk** [comment]
Note isodate will stop working in Python 3.10 due to a `DeprecationWarning` introduced in Python 3.8 becoming a `TypeError` in Python 3.10.

Please see https://github.com/gweis/isodate/pull/68 for a fix.

Python 3.10 is due out in just three weeks, so I recommend a release before then.

@gweis If you need a hand with a release, I'd be happy to help out.

**Comment by hugovk** [comment]
I've moved my fork to an organisation, it's now at https://github.com/isodate/isodate/.

I've modernised things: dropped EOL Python, added automated release notes and deploys, converted all the tests to pytest, formatted with Black and isort, added pre-commit and linters.

If anyone else is interested in joining the team, please open an issue over there, and also PRs welcome over there!

It's also worth mentioning https://github.com/bolsote/isoduration by @bolsote as doing something similar to isodate. isoduration looks well maintained and switching to isoduration may be a better long term aim rather than continuing with isodate[2].

I'll also check the existing PRs/issues here and see what else can go to https://github.com/isodate/isodate/. Thanks!

**Comment by hugovk** [comment]
And I should mention, I think the aim of the fork should to be conservative in what it accepts, especially given the existence of https://github.com/bolsote/isoduration.

See also https://github.com/bolsote/isoduration/issues/9#issuecomment-864257454 which reviews the open issues here and shows which are already fixed/improved/planned/irrelevant in isoduration or should not be fixed if incompatible with the standard.

**Comment by hugovk** [comment]
The good news is @gweis is back and has made a new release! 🚀

So the fork is no longer needed and I'll archive the repo.

Can this issue be closed?
